# Site settings
title: 朱小怂
SEOTitle: 小怂的博客 | little-Song's Blog
header-img: img/home-bg.jpg
email: zhujingquanhit@126.com
description: "自动驾驶相关 | 朱景泉，Tech & Geek Lover，Software Engineer in Autonomous vehicles | 这里是 @景泉 的个人博客，与你一起发现更大的世界。"
keyword: "朱景泉, ZJQ朱景泉, Hux, 自动驾驶,环境感知,SLAM 朱景泉的博客, ZJQ Blog, 博客, 个人网站"
url: "47.101.151.112"              # your host, for absolute URL
baseurl: "/huxblog-boilerplate"         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     huxpro
zhihu_username:     zhujingquan
github_username:    zhujingquan
#twitter_username:  huxpro
facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 2fdf679f320751627964d07dfa85b498
# Google Analytics
ga_track_id: 'UA-113187235-2'            # Format: UA-xxxxxx-xx
ga_domain: 47.101.151.112



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，看看书，<br>To improve is to change, to be perfect is to change often."
sidebar-avatar: /img/HIT.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    # {
    #     title: "Hux Blog",
    #     href: "http://huangxuan.me"
    # },{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
]
